package com.aserbao.database.database.greendao.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.aserbao.database.database.beans.CreditCard;
import com.aserbao.database.database.beans.IdCard;
import com.aserbao.database.database.beans.Student;
import com.aserbao.database.database.beans.StudentAndTeacherBean;
import com.aserbao.database.database.beans.SuperThing;
import com.aserbao.database.database.beans.Teacher;
import com.aserbao.database.database.beans.Thing;
import com.example.base.Students;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig superThingDaoConfig;
    private final DaoConfig idCardDaoConfig;
    private final DaoConfig thingDaoConfig;
    private final DaoConfig creditCardDaoConfig;
    private final DaoConfig studentAndTeacherBeanDaoConfig;
    private final DaoConfig studentDaoConfig;
    private final DaoConfig teacherDaoConfig;
    private final DaoConfig studentsDaoConfig;

    private final SuperThingDao superThingDao;
    private final IdCardDao idCardDao;
    private final ThingDao thingDao;
    private final CreditCardDao creditCardDao;
    private final StudentAndTeacherBeanDao studentAndTeacherBeanDao;
    private final StudentDao studentDao;
    private final TeacherDao teacherDao;
    private final StudentsDao studentsDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        superThingDaoConfig = daoConfigMap.get(SuperThingDao.class).clone();
        superThingDaoConfig.initIdentityScope(type);

        idCardDaoConfig = daoConfigMap.get(IdCardDao.class).clone();
        idCardDaoConfig.initIdentityScope(type);

        thingDaoConfig = daoConfigMap.get(ThingDao.class).clone();
        thingDaoConfig.initIdentityScope(type);

        creditCardDaoConfig = daoConfigMap.get(CreditCardDao.class).clone();
        creditCardDaoConfig.initIdentityScope(type);

        studentAndTeacherBeanDaoConfig = daoConfigMap.get(StudentAndTeacherBeanDao.class).clone();
        studentAndTeacherBeanDaoConfig.initIdentityScope(type);

        studentDaoConfig = daoConfigMap.get(StudentDao.class).clone();
        studentDaoConfig.initIdentityScope(type);

        teacherDaoConfig = daoConfigMap.get(TeacherDao.class).clone();
        teacherDaoConfig.initIdentityScope(type);

        studentsDaoConfig = daoConfigMap.get(StudentsDao.class).clone();
        studentsDaoConfig.initIdentityScope(type);

        superThingDao = new SuperThingDao(superThingDaoConfig, this);
        idCardDao = new IdCardDao(idCardDaoConfig, this);
        thingDao = new ThingDao(thingDaoConfig, this);
        creditCardDao = new CreditCardDao(creditCardDaoConfig, this);
        studentAndTeacherBeanDao = new StudentAndTeacherBeanDao(studentAndTeacherBeanDaoConfig, this);
        studentDao = new StudentDao(studentDaoConfig, this);
        teacherDao = new TeacherDao(teacherDaoConfig, this);
        studentsDao = new StudentsDao(studentsDaoConfig, this);

        registerDao(SuperThing.class, superThingDao);
        registerDao(IdCard.class, idCardDao);
        registerDao(Thing.class, thingDao);
        registerDao(CreditCard.class, creditCardDao);
        registerDao(StudentAndTeacherBean.class, studentAndTeacherBeanDao);
        registerDao(Student.class, studentDao);
        registerDao(Teacher.class, teacherDao);
        registerDao(Students.class, studentsDao);
    }
    
    public void clear() {
        superThingDaoConfig.clearIdentityScope();
        idCardDaoConfig.clearIdentityScope();
        thingDaoConfig.clearIdentityScope();
        creditCardDaoConfig.clearIdentityScope();
        studentAndTeacherBeanDaoConfig.clearIdentityScope();
        studentDaoConfig.clearIdentityScope();
        teacherDaoConfig.clearIdentityScope();
        studentsDaoConfig.clearIdentityScope();
    }

    public SuperThingDao getSuperThingDao() {
        return superThingDao;
    }

    public IdCardDao getIdCardDao() {
        return idCardDao;
    }

    public ThingDao getThingDao() {
        return thingDao;
    }

    public CreditCardDao getCreditCardDao() {
        return creditCardDao;
    }

    public StudentAndTeacherBeanDao getStudentAndTeacherBeanDao() {
        return studentAndTeacherBeanDao;
    }

    public StudentDao getStudentDao() {
        return studentDao;
    }

    public TeacherDao getTeacherDao() {
        return teacherDao;
    }

    public StudentsDao getStudentsDao() {
        return studentsDao;
    }

}
