/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "BeatDetektor.h"

/* Header for class com_aserbao_aserbaosandroid_functions_how_create_so_create_spot_BeatDetector */

#ifndef _Included_com_aserbao_aserbaosandroid_functions_how_create_so_create_spot_BeatDetector
#define _Included_com_aserbao_aserbaosandroid_functions_how_create_so_create_spot_BeatDetector
#ifdef __cplusplus
extern "C" {
#endif
    static jfieldID _get_self_id(JNIEnv *env, jobject thisObj)
    {
        static int init = 0;
        static jfieldID fidSelfPtr;
        if(!init)
        {
            jclass thisClass = env->GetObjectClass(thisObj);
            fidSelfPtr = env->GetFieldID(thisClass, "self_ptr", "J");
        }
        return fidSelfPtr;
    }

    static BeatDetektor *_get_self(JNIEnv *env, jobject thisObj)
    {
        jlong selfPtr = env->GetLongField(thisObj, _get_self_id(env, thisObj));
        return *(BeatDetektor**)&selfPtr;
    }

    static void _set_self(JNIEnv *env, jobject thisObj, BeatDetektor *self)
    {
        jlong selfPtr = *(jlong*)&self;
        env->SetLongField(thisObj, _get_self_id(env, thisObj), selfPtr);
    }

    /*
     * Class:     com_aserbao_aserbaosandroid_functions_how_create_so_create_spot_BeatDetector
     * Method:    init
     * Signature: (FF)V
     */
    JNIEXPORT void JNICALL Java_com_aserbao_aserbaosandroid_functions_how_1create_1so_create_1spot_BeatDetector_init
      (JNIEnv * env, jobject thisObj, jfloat a, jfloat b)
    {
        BeatDetektor *self = new BeatDetektor(a, b);
        _set_self(env, thisObj, self);
    }

    /*
     * Class:     com_aserbao_aserbaosandroid_functions_how_create_so_create_spot_BeatDetector
     * Method:    process
     * Signature: (F[F)V
     */
    JNIEXPORT void JNICALL Java_com_aserbao_aserbaosandroid_functions_how_1create_1so_create_1spot_BeatDetector_process
      (JNIEnv *env, jobject thisObj, jfloat jfloat1, jfloatArray jfloatArray1){
        BeatDetektor *self = _get_self(env, thisObj);
//        std::vector<float> vec;
        self->process(jfloat1, reinterpret_cast<std::vector<float> &>(jfloatArray1));
    }

/*
 * Class:     com_aserbao_aserbaosandroid_functions_how_create_so_create_spot_BeatDetector
 * Method:    getWinVal
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_aserbao_aserbaosandroid_functions_how_1create_1so_create_1spot_BeatDetector_getWinVal
  (JNIEnv *env, jobject thisObj){
    BeatDetektor *self = _get_self(env, thisObj);
    return self->win_val;
}

/*
 * Class:     com_aserbao_aserbaosandroid_functions_how_create_so_create_spot_BeatDetector
 * Method:    getBeatCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_aserbao_aserbaosandroid_functions_how_1create_1so_create_1spot_BeatDetector_getBeatCount
  (JNIEnv *env, jobject thisObj){
    BeatDetektor *self = _get_self(env, thisObj);
    return self->beat_counter;
}

#ifdef __cplusplus
}
#endif
#endif
