/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aserbao_aserbaosandroid_functions_how_create_so_create_spot_BeatDetector */

#ifndef _Included_com_aserbao_aserbaosandroid_functions_how_create_so_create_spot_BeatDetector
#define _Included_com_aserbao_aserbaosandroid_functions_how_create_so_create_spot_BeatDetector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_aserbao_aserbaosandroid_functions_how_create_so_create_spot_BeatDetector
 * Method:    getSimpleInfoFromOne
 * Signature: (F[F)V
 */
JNIEXPORT void JNICALL Java_com_aserbao_aserbaosandroid_functions_how_1create_1so_create_1spot_BeatDetector_getSimpleInfoFromOne
  (JNIEnv *, jclass, jfloat, jfloatArray);

/*
 * Class:     com_aserbao_aserbaosandroid_functions_how_create_so_create_spot_BeatDetector
 * Method:    getWinVal
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_aserbao_aserbaosandroid_functions_how_1create_1so_create_1spot_BeatDetector_getWinVal
  (JNIEnv *, jclass);

/*
 * Class:     com_aserbao_aserbaosandroid_functions_how_create_so_create_spot_BeatDetector
 * Method:    getBeatCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_aserbao_aserbaosandroid_functions_how_1create_1so_create_1spot_BeatDetector_getBeatCount
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
