/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aserbao_aserbaosandroid_functions_how_create_so_create_spot_BeatDetector */

#ifndef _Included_com_aserbao_aserbaosandroid_functions_how_create_so_create_spot_BeatDetector
#define _Included_com_aserbao_aserbaosandroid_functions_how_create_so_create_spot_BeatDetector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_aserbao_aserbaosandroid_functions_how_create_so_create_spot_BeatDetector
 * Method:    getSimpleInfoFromOne
 * Signature: ([Ljava/lang/Short;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_aserbao_aserbaosandroid_functions_how_1create_1so_create_1spot_BeatDetector_getSimpleInfoFromOne
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
