/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aserbao_aserbaosandroid_AudioAndVideo_jnis_javaCallC_Mp3Encoder */

#ifndef _Included_com_aserbao_aserbaosandroid_AudioAndVideo_jnis_javaCallC_Mp3Encoder
#define _Included_com_aserbao_aserbaosandroid_AudioAndVideo_jnis_javaCallC_Mp3Encoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_aserbao_aserbaosandroid_AudioAndVideo_jnis_javaCallC_Mp3Encoder
 * Method:    encode
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_aserbao_aserbaosandroid_AudioAndVideo_jnis_javaCallC_Mp3Encoder_encode
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
